# Parts of this file are based on:
#   url: https://github.com/al3x/sovereign/blob/a48a9941009cc1f18450d01cc7cf4f067ece3fae/roles/tarsnap/tasks/tarsnap.yml
#   contributors:  al3x jplock lvillani lukecyca jsravn bcachet alexdunae pdebruic
# The sovereign project source and this derivative work are licensed under the GNU General Public License v3.

- name: Install dependencies for Tarsnap and Tarsnapper
  apt: pkg={{ item }} state=installed
  with_items:
    - ca-certificates
    - python-pip
    - python-virtualenv
    - git

- name: Check if tarsnap is installed
  shell: tarsnap --version
  register: tarsnap_installed
  changed_when: "tarsnap_installed.stderr != ''"
  ignore_errors: yes

- name: Add tarsnap apt key
  when: tarsnap_installed|failed
  apt_key:
    url: https://pkg.tarsnap.com/tarsnap-deb-packaging-key.asc
    state: present

- name: Add tarsnap apt repository
  when: tarsnap_installed|failed
  apt_repository:
    repo: "deb http://pkg.tarsnap.com/deb/{{ ansible_distribution_release }} ./"
    state: present

- name: Update apt cache
  when: tarsnap_installed|failed
  apt: update_cache=yes

- name: Install tarsnap and possible key updates via apt
  when: tarsnap_installed|failed
  apt: "pkg={{ item }} state=installed"
  with_items:
    - tarsnap
    - tarsnap-archive-keyring

- name: Create Tarsnap cache directory
  file: state=directory path={{ tarsnap_cache }} owner=root group=root mode=700

- name: Install Tarsnap configuration file
  template: src=tarsnap.conf dest={{ tarsnap_config_file }} owner=root group=root mode=600

- name: Install Tarsnap key file
  copy:
    content: "{{ tarsnap_key_content }}"
    dest: "{{ tarsnap_key_file }}"
    owner: root
    group: root
    mode: 0600

- name: Install alternate Tarsnap key file
  copy:
    content: "{{ tarsnap_key_alternate_content }}"
    dest: "{{ tarsnap_key_alternate_file }}"
    owner: root
    group: root
    mode: 0600
  when: tarsnap_key_alternate_content is defined

- name: Create Tarsnapper base directory and jobs include directory
  file:
    state: directory
    path: "{{ tarsnapper_include_jobs_path }}"
    owner: root
    group: root
    mode: u=rwX,g=,o=
    recurse: yes

- name: Create virtual env for tarsnapper
  command: virtualenv {{ tarsnapper_virtualenv_path }} --no-site-packages
           creates={{ tarsnapper_virtualenv_path }}/bin/activate

- name: Install tarsnapper to virtualenv
  # we use the shell module because in order to install from a git commit we need to set "editable: false" and that's
  # only supported in ansible 2.0 or later, which isn't out as of 2015-01-09.
  shell: '. {{ tarsnapper_virtualenv_path }}/bin/activate && pip install "{{ tarsnapper_package_name }}"'
  args:
    creates: "{{ tarsnapper_virtualenv_path }}/bin/tarsnapper"

- name: Correct virtual env permissions
  file:
    state: directory
    path: "{{ tarsnapper_virtualenv_path }}"
    owner: root
    group: root
    mode: u=rwX,g=,o=
    recurse: yes

- name: Install tarsnapper configuration file
  template: src=tarsnapper.conf dest={{ tarsnapper_config_file }} owner=root group=root mode=600

- name: Install tarsnapper backup script
  template: src=tarsnapper.sh dest={{ tarsnapper_script_file }} owner=root group=root mode=700

- name: Configure tarsnap logrotate
  template: src=etc_logrotate_tarsnap dest=/etc/logrotate.d/tarsnap owner=root group=root mode=0644

- name: Install tarsnapper cronjob
  cron:
    name: "{{ tarsnapper_cron_job_name }} "
    job: "{{ tarsnapper_script_file }} > /dev/null"
    minute: "{{ tarsnapper_cron_minute }}"
    hour: "{{ tarsnapper_cron_hour }}"
    day: "{{ tarsnapper_cron_day }}"
    month: "{{ tarsnapper_cron_month }}"
    weekday: "{{ tarsnapper_cron_weekday }}"
